name: Build Windows Bundle

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      RELEASE_DIR: release-assets

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare release dir
        run: |
          rm -rf "$RELEASE_DIR"
          mkdir -p "$RELEASE_DIR"

      - name: Download nssm (2.24)
        run: |
          NSSM_URL="https://nssm.cc/release/nssm-2.24.zip"
          curl -L -o /tmp/nssm.zip "$NSSM_URL"
          unzip -q /tmp/nssm.zip -d /tmp/nssm_unpack
          find /tmp/nssm_unpack -type f -iname "nssm.exe" -exec cp {} "$RELEASE_DIR/" \;
          ls -la "$RELEASE_DIR" || true

      - name: Download latest PHP 8.4 x64 build (automatic detection)
        shell: bash
        run: |
          LISTING="$(curl -s https://windows.php.net/downloads/releases/)"
          PHP_ZIP=$(echo "$LISTING" \
            | egrep -o 'php-8\.4\.[0-9]+-Win32-vs1[67]-x64\.zip' \
            | sort -V | tail -n1)
          if [ -z "$PHP_ZIP" ]; then
            echo "Fallback: Using php-8.4.13-Win32-vs17-x64.zip"
            PHP_ZIP="php-8.4.13-Win32-vs17-x64.zip"
          fi
          echo "Downloading $PHP_ZIP..."
          curl -L -o /tmp/php8.4.zip "https://windows.php.net/downloads/releases/$PHP_ZIP"
          unzip -q /tmp/php8.4.zip -d /tmp/php_unpack
          mkdir -p "$RELEASE_DIR/php"
          cp -r /tmp/php_unpack/* "$RELEASE_DIR/php/" || true
          cp "$RELEASE_DIR/php/php.ini-production" "$RELEASE_DIR/php/php.ini"
          # Enable required extensions
          echo "extension=intl" >> "$RELEASE_DIR/php/php.ini"
          echo "extension=sockets" >> "$RELEASE_DIR/php/php.ini"
          ls -la "$RELEASE_DIR/php" | head -n 20

      - name: Add eps.phar (from repo)
        run: |
          if [ ! -f bin/eps.phar ]; then
            echo "ERROR: bin/eps.phar not found in repository."
            exit 1
          fi
          cp bin/eps.phar "$RELEASE_DIR/"

      - name: Create Windows BAT scripts
        run: |
          # === INSTALL SCRIPT ===
          cat > "$RELEASE_DIR/install-eps-service.bat" <<'BAT'
          @echo off
          REM install-eps-service.bat
          REM Installs eps.phar as a Windows service using nssm.exe
          SETLOCAL
          set "SVCNAME=EscPosPrinterServer"
          set "BASEDIR=%~dp0"
          set "NSSM=%BASEDIR%nssm.exe"
          set "PHP=%BASEDIR%php\php.exe"
          set "EPS=%BASEDIR%eps.phar"

          if not exist "%NSSM%" (
            echo nssm.exe not found in %BASEDIR%
            exit /b 1
          )
          if not exist "%PHP%" (
            echo php.exe not found in %BASEDIR%php\
            exit /b 2
          )
          if not exist "%EPS%" (
            echo eps.phar not found in %BASEDIR%
            exit /b 3
          )

          "%NSSM%" install "%SVCNAME%" "%PHP%" "%EPS%"
          "%NSSM%" set "%SVCNAME%" AppDirectory "%BASEDIR%"
          "%NSSM%" start "%SVCNAME%"
          echo Service "%SVCNAME%" installed and started.
          ENDLOCAL
          BAT

          # === STOP SCRIPT ===
          cat > "$RELEASE_DIR/stop-eps-service.bat" <<'BAT'
          @echo off
          REM stop-eps-service.bat
          REM Stops the eps Windows service
          SETLOCAL
          set "SVCNAME=EscPosPrinterServer"
          set "BASEDIR=%~dp0"
          set "NSSM=%BASEDIR%nssm.exe"

          if not exist "%NSSM%" (
            echo nssm.exe not found in %BASEDIR%
            exit /b 1
          )

          echo Stopping service "%SVCNAME%"...
          "%NSSM%" stop "%SVCNAME%"
          echo Done.
          ENDLOCAL
          BAT

          # === UNINSTALL SCRIPT ===
          cat > "$RELEASE_DIR/uninstall-eps-service.bat" <<'BAT'
          @echo off
          REM uninstall-eps-service.bat
          REM Stops and removes the eps Windows service
          SETLOCAL
          set "SVCNAME=EscPosPrinterServer"
          set "BASEDIR=%~dp0"
          set "NSSM=%BASEDIR%nssm.exe"

          if not exist "%NSSM%" (
            echo nssm.exe not found in %BASEDIR%
            exit /b 1
          )

          echo Stopping service "%SVCNAME%"...
          "%NSSM%" stop "%SVCNAME%"
          timeout /t 2 >nul
          echo Removing service "%SVCNAME%"...
          "%NSSM%" remove "%SVCNAME%" confirm
          echo Service "%SVCNAME%" uninstalled.
          ENDLOCAL
          BAT

      - name: Package release assets
        run: |
          ZIP_NAME="eps-windows-bundle.zip"
          cd "$RELEASE_DIR"
          zip -r "../$ZIP_NAME" ./*
          cd ..
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          ls -lh "$ZIP_NAME"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ZIP_NAME }}
